rules:
  self-repository:
    ignore:
      # actionlint v1.7.12 rejects self-repository workflow references.
      # Migrate and remove this exception when actionlint supports them:
      # https://github.com/altendky/scansor/issues/75
      - ci.yml
