from __future__ import annotations

import io
import struct

import numpy as np
import pytest

from scansor._plyio import Element, ScalarProperty, make_header
from scansor.mesh_display_ply import (
    FACE_DIGITS,
    VERTEX_DIGITS,
    DisplayPlyReader,
    display_header,
    id_values,
)
from scansor.mesh_errors import MeshImportError


def raw_export() -> bytes:
    header = display_header("validity", 3, 1)
    vertices = b"".join(
        struct.pack(
            "<dddBBBfffddffff", *xyz, 40, 170, 80, 0, 0, 0, 2, 1, index, 0, 0, 0
        )
        for index, xyz in enumerate(((0, 0, 0), (3, 0, 0), (0, 4, 0)))
    )
    return header.raw + vertices + struct.pack("<Biii", 3, 0, 1, 2)


@pytest.mark.parametrize(
    "mutation",
    (
        "short-coordinate",
        "short-id",
        "short-face",
        "trailing",
        "face-count",
        "negative-index",
        "upper-index",
        "nonfinite-coordinate",
        "invalid-status",
        "negative-area",
        "fractional-id",
    ),
)
def test_display_reader_rejects_malformed_export(mutation: str) -> None:
    raw = bytearray(raw_export())
    header_size = len(display_header("validity", 3, 1).raw)
    if mutation == "short-coordinate":
        del raw[header_size + 1 :]
    elif mutation == "short-id":
        del raw[header_size + 60 :]
    elif mutation == "short-face":
        del raw[-1:]
    elif mutation == "trailing":
        raw.extend(b"x")
    elif mutation == "face-count":
        raw[-13] = 2
    elif mutation in ("negative-index", "upper-index"):
        struct.pack_into(
            "<i", raw, len(raw) - 12, -1 if mutation == "negative-index" else 3
        )
    elif mutation == "nonfinite-coordinate":
        struct.pack_into("<d", raw, header_size, float("nan"))
    elif mutation == "invalid-status":
        struct.pack_into("<f", raw, header_size + 27, 1)
    elif mutation == "negative-area":
        struct.pack_into("<d", raw, header_size + 39, -2)
    else:
        struct.pack_into("<f", raw, header_size + 55, 0.5)
    with pytest.raises(MeshImportError):
        DisplayPlyReader(io.BytesIO(raw), "validity", chunk_rows=1).validate_all()


def test_resave_reader_uses_actual_property_types_and_exposes_loss() -> None:
    props = (
        *(ScalarProperty(axis, "float") for axis in ("x", "y", "z")),
        ScalarProperty("scalar_raw_area", "double"),
        ScalarProperty("scalar_weight", "float"),
        *(ScalarProperty(name, "float") for name in VERTEX_DIGITS),
        ScalarProperty("renamed_status", "float"),
    )
    header = make_header((Element("vertex", 1, props),))
    raw = header.raw + struct.pack(
        "<fffdffffff", 1, 2, 3, float("-inf"), 0, 65535, 65535, 65535, 65535, 2
    )
    reader = DisplayPlyReader(io.BytesIO(raw), "weights", resaved=True)
    assert reader.fields()["scalar_raw_area"] == "double"
    assert "scalar_contribution_status" not in reader.fields()
    assert "renamed_status" in reader.fields()
    rows = reader.read_range("vertex", 0, 1)
    assert np.isneginf(rows["scalar_raw_area"][0])
    assert rows["scalar_weight"][0] == 0
    assert int(id_values(rows, VERTEX_DIGITS)[0]) == 2**64 - 1
    assert reader.faces == 0
    with pytest.raises(MeshImportError, match="dropped or renamed"):
        _ = id_values(rows, FACE_DIGITS)
    with pytest.raises(MeshImportError):
        _ = DisplayPlyReader(io.BytesIO(raw), "weights")


def test_resave_profile_bounds_extra_properties_and_actual_row_bytes() -> None:
    props = tuple(ScalarProperty(axis, "double") for axis in ("x", "y", "z"))
    props += tuple(ScalarProperty("extra_" + str(i), "double") for i in range(30))
    header = make_header((Element("vertex", 0, props),))
    with pytest.raises(MeshImportError, match="at most 32"):
        _ = DisplayPlyReader(io.BytesIO(header.raw), "validity", resaved=True)


def test_display_range_bound_applies_even_when_record_bytes_would_fit() -> None:
    reader = DisplayPlyReader(io.BytesIO(raw_export()), "validity", chunk_rows=1)
    with pytest.raises(MeshImportError, match="row bound"):
        _ = reader.read_range("face", 0, 2)


def test_observed_viewer_object_info_preserves_raw_header_and_offsets() -> None:
    raw = raw_export().replace(
        b"element vertex", b"obj_info Generated by CloudCompare!\nelement vertex", 1
    )
    reader = DisplayPlyReader(io.BytesIO(raw), "validity", resaved=True)
    assert reader.layout.header.raw == raw[: raw.index(b"end_header\n") + 11]
    assert tuple(reader.read_range("vertex", 1, 2)["x"]) == (3,)
    assert reader.read_range("face", 0, 1)["vertex_indices"]["values"].tolist() == [
        [0, 1, 2]
    ]
    with pytest.raises(MeshImportError):
        _ = DisplayPlyReader(io.BytesIO(raw), "validity")
    with pytest.raises(MeshImportError):
        _ = DisplayPlyReader(
            io.BytesIO(raw.replace(b"obj_info Generated", b"unknown_info Generated")),
            "validity",
            resaved=True,
        )
